const plugin = require('tailwindcss/plugin');

module.exports = {
  mode: 'jit',
  content: [
    './**/*.php',
    './assets/js/**/*.js',
  ],
  theme: {
    extend: {
      fontFamily: {
        primary: ['Poppins', 'sans-serif'],
        secondary: ['Poppins', 'sans-serif'],
        tertiary: ['Poppins', 'sans-serif'],
      },
      colors: {
        primary: {
          DEFAULT: '##F68D2E',
          light: '#025A70',
          dark: '#c54f06',
        },
        secondary: {
          DEFAULT: '#025A70',
          light: '#1e1f3d',
          dark: '#4e4f7e',
        },
        background: {
          DEFAULT: '#ffffff',
          light: '#EFF5EC',
          dark: '#000000',
        },
        accent: {
          greenLight: '#50B847',
          greenDark: '#00672F',
          orange: '#F16623',
          yellowLight: '#FFF100',
          yellowDark: '#FDCC05',
        },
        neutral: {
          light: '#F5F5F5',
          DEFAULT: '#E7E7E7',
          dark: '#FFF6F1',
        },
        highlight: {
          light: '#FFF9E2',
          yellow: '#FFFAE8',
          orange: '#FDCC05',
        },
        text: {
          primary: '#1D2939',
          secondary: '#ffffff',
          accent: '#F6AD55',
        },
      },
      fontSize: {
        base: '16px',
      },
      width: {
        'container-md': '1084px',
        'container-lg': '1280px',
        'container': '1440px',
      },
      maxWidth: {
        'container': '1440px',
        'xxs': '320px',
        'xs': '480px',
        'mob': '575px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        'xxl': '1440px',
        'ultrawide': '1920px',
      },
      borderRadius: {
        'custom': '0px',
        'custom-sm': '4px',
        'custom-md': '8px',
        'custom-lg': '16px',
        'custom-xl': '40px',
        'custom-full': '100%',
        'btn': '0px',
      },
    },
    screens: {
      xxs: '320px',
      xs: '480px',
      mob: '575px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      xxl: '1440px',
      ultrawide: '1920px',
    },
    container: {
      center: true,
      padding: '1.5rem',
      screens: {
        xxs: '320px',
        xs: '480px',
        mob: '575px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        xxl: '1440px',
        ultrawide: '1920px',
      },
    },
  },
  variants: {
    extend: {
      backgroundColor: ['not-first'],
      display: ['before', 'after'],
    },
  },
  plugins: [
    require('tailwindcss-pseudo')({
      empty: true,
      before: true,
      after: true,
    }),
  ],
  safelist: [
    // Static width classes
    'absolute',
    'relative',
    'top-0',
    'left-0',
    'right-0',
    'bottom-0',
    'inset-0',
    'max-w-[745px]',
    'fit-content',
    'w-1/2',
    'w-1/3',
    'w-2/3',
    'w-1/4',
    'w-2/4',
    'w-3/4',
    'w-1/5',
    'w-2/5',
    'w-3/5',
    'w-4/5',
    'w-1/6',
    'w-2/6',
    'w-3/6',
    'w-4/6',
    'w-5/6',
    'w-1/12',
    'w-2/12',
    'w-3/12',
    'w-4/12',
    'w-5/12',
    'w-6/12',
    'w-7/12',
    'w-8/12',
    'w-9/12',
    'w-10/12',
    'w-11/12',
    'w-full',
    // Container classes
    'container',
    'container-md',
    'max-w-container',
    'max-w-container-md',
    'max-w-container-lg',
    'max-w-xxs',
    'max-w-xs',
    'max-w-mob',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-xxl',
    'max-w-ultrawide',
    // Width classes
    ...Array.from({ length: 100 }, (_, i) => `w-[${i + 1}%]`),
    ...Array.from({ length: 100 }, (_, i) => `xs:w-[${i + 1}%]`),
    ...Array.from({ length: 100 }, (_, i) => `mobs:w-[${i + 1}%]`),
    ...Array.from({ length: 100 }, (_, i) => `sm:w-[${i + 1}%]`),
    ...Array.from({ length: 100 }, (_, i) => `md:w-[${i + 1}%]`),
    ...Array.from({ length: 100 }, (_, i) => `lg:w-[${i + 1}%]`),
    ...Array.from({ length: 100 }, (_, i) => `xl:w-[${i + 1}%]`),
    ...Array.from({ length: 100 }, (_, i) => `xxl:w-[${i + 1}%]`),
    ...Array.from({ length: 100 }, (_, i) => `ultrawide:w-[${i + 1}%]`),
    ...Array.from({ length: 100 }, (_, i) => `md:w-[${i + 1}%]`),
    // Dynamic gap classes
    ...Array.from({ length: 101 }, (_, i) => `gap-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:gap-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `md:gap-[${i}px]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:gap-[${i}px]`),
    // Dynamic padding-y classes
    ...Array.from({ length: 101 }, (_, i) => `py-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `xs:py-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `mobs:py-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:py-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `md:py-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:py-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:py-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:py-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:py-[${i + 1}%]`),
    // Dynamic padding-top and padding-bottom classes
    ...Array.from({ length: 101 }, (_, i) => `pt-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `pb-[${i + 1}%]`),
    //`xs
    ...Array.from({ length: 101 }, (_, i) => `xs:pt-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `xs:pb-[${i + 1}%]`),
    //mobs
    ...Array.from({ length: 101 }, (_, i) => `mobs:pt-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `mobs:pb-[${i + 1}%]`),
    //sm
    ...Array.from({ length: 101 }, (_, i) => `sm:pt-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `sm:pb-[${i + 1}%]`),
    //md
    ...Array.from({ length: 101 }, (_, i) => `md:pt-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `md:pb-[${i + 1}%]`),
    //lg
    ...Array.from({ length: 101 }, (_, i) => `lg:pt-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `lg:pb-[${i + 1}%]`),
    //xl
    ...Array.from({ length: 101 }, (_, i) => `xl:pt-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `xl:pb-[${i + 1}%]`),
    //xxl
    ...Array.from({ length: 101 }, (_, i) => `xxl:pt-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `xxl:pb-[${i + 1}%]`),
    //ultrawide
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:pt-[${i + 1}%]`),
    ...Array.from({ length: 101 }, (_, i) => `ultrawide:pb-[${i + 1}%]`),
    // Dynamic rounded classes
    ...Array.from({ length: 101 }, (_, i) => `rounded-[${i}px]`),
  ],
};
